
crop_dir: '/home/mleutenegger/Data/20170216_p32_s3_ac1/crop/'

# Cellprofiler output info:
cp_dir: '/home/mleutenegger/Data/20170216_p32_s3_ac1/cpoutput/'
stack_dir:
  path: '/home/mleutenegger/Code/20170324_spherpro_testing/stacks/'
stack_relations: '/home/mleutenegger/Code/20170324_spherpro_testing/stack_relations.csv'
cpoutput:
  cells_csv:
    path: 'RescaledCells.csv'
  relation_csv:
    path: 'Object relationships.csv'
  images_csv:
    path: 'Image.csv'

# Experiment layout info:
layout_csv:
  path: '/home/mleutenegger/Code/20170324_spherpro_testing/testlayout.csv'
  plate_col: 'Plate'
  well_col: 'TargetWell'
  condition_col: 'Compound'
  control_col: 'isControl'

# Barcode Info:
barcode_csv:
  path: '/home/vitoz/Data/60-wellplate_102-104-105-106-108-110-Pd_113-115-In_BarcodingKey.csv'
  well_col: 'Mass'
  sep: ';'

# wells_csv:
  # path: ''


# Pannel Info:
pannel_csv:
  path: '/home/mleutenegger/Git/SpheroidSignaling/20170216_p32_s3_ac1/20170216_panel.csv'
